WIP

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -20,6 +20,38 @@
 
 @burly@
 
+usage() {
+    local error="${1:-}"
+
+    if [ -n "${error}" ]
+    then
+        printf "%b %s\n\n" "$(red "ERROR:")" "${*}"
+    fi
+
+    cat <<EOF
+Usage: ${0} [-hvy] [-s <scheme>]
+
+A script that installs ActiveMQ Artemis
+
+Options:
+  -h            Print this help text and exit
+  -i            Operate in interactive mode
+  -s <scheme>   Select an installation scheme (default "home")
+  -v            Print detailed logging to the console
+
+Installation schemes:
+  home          Install to ~/.local and ~/.config
+  opt           Install to /opt, /var/opt, and /etc/opt
+EOF
+
+    if [ -n "${error}" ]
+    then
+        exit 1
+    fi
+
+    exit 0
+}
+
 # func <output-dir> -> release_version=<version>, release_file=<file>
 fetch_latest_artemis_release() {
     local output_dir="$1"
@@ -91,38 +123,6 @@ fetch_latest_artemis_release() {
 
     assert test -n "${release_version}"
     assert test -f "${release_file}"
-}
-
-usage() {
-    local error="${1:-}"
-
-    if [ -n "${error}" ]
-    then
-        printf "%b %s\n\n" "$(red "ERROR:")" "${*}"
-    fi
-
-    cat <<EOF
-Usage: ${0} [-hvy] [-s <scheme>]
-
-A script that installs ActiveMQ Artemis
-
-Options:
-  -h            Print this help text and exit
-  -i            Operate in interactive mode
-  -s <scheme>   Select an installation scheme (default "home")
-  -v            Print detailed logging to the console
-
-Installation schemes:
-  home          Install to ~/.local and ~/.config
-  opt           Install to /opt, /var/opt, and /etc/opt
-EOF
-
-    if [ -n "${error}" ]
-    then
-        exit 1
-    fi
-
-    exit 0
 }
 
 # func <script-file> <artemis-instance-dir>
